### ISSUE TITLE
FATA[0000] getting the runtime version: rpc error: code = Internal desc = stream terminated by RST_STREAM with error code: PROTOCOL_ERROR

### ISSUE THREAD

**Issue by Ruilkyu** [cri-o/containrs#437] opened 2021-03-06 13:23 UTC

**Comment by saschagrunert** [comment] 2021-03-08 08:29
Hey @Ruilkyu, this is a known issue and a duplicate of https://github.com/cri-o/containrs/issues/34
/close

**Closed by saschagrunert** 2021-03-08 08:29 UTC
